Title = "Star Trek (The Original Series) Log Entries"
Description = "Transcriptions of all log entries in Star Trek TOS, sourced from http://www.chakoteya.net/StarTrek"
Author = "gearsix <gearsix@tuta.io>"
